// Generated by CoffeeScript 1.3.3
(function() {

  window.app = (function() {
    var modules;
    modules = {};
    return {
      module: function(name) {
        if (modules[name]) {
          return modules[name];
        }
        return modules[name] = {};
      },
      require: function(name) {
        if (modules[name]) {
          return modules[name];
        } else {
          throw 'ModuleError: No module registered with name ' + name;
        }
      }
    };
  })();

  _.extend(window.app, Backbone.Events);

  $(document).ready(function() {
    var Router;
    Router = app.module("Routers").Router;
    return app.router = new Router;
  });

}).call(this);
