// Generated by CoffeeScript 1.3.3
(function() {

  L.Control.Locate = L.Control.extend({
    options: {
      position: 'topright'
    },
    initialize: function(options) {
      return L.Util.setOptions(this, options);
    },
    onAdd: function(map) {
      var className, container;
      className = 'leaflet-control-locate';
      container = L.DomUtil.create('div', className);
      this._map = map;
      this._createButton('Locate Me', className, container, this._locate, this);
      return container;
    },
    _createButton: function(title, className, container, fn, context) {
      var link;
      link = L.DomUtil.create('a', className, container);
      link.href = '#';
      link.title = title;
      L.DomEvent.on(link, 'click', L.DomEvent.preventDefault).on(link, 'click', fn, context);
      L.DomEvent.disableClickPropagation(link);
      return link;
    },
    _locate: function() {
      return this._map.locate({
        setView: true,
        maxZoom: this.options.maxZoom || 12
      });
    }
  });

}).call(this);
