// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  (function(exports, B, L) {
    return exports.MapModel = (function(_super) {

      __extends(MapModel, _super);

      function MapModel() {
        return MapModel.__super__.constructor.apply(this, arguments);
      }

      MapModel.prototype.layers = [];

      MapModel.prototype.defaults = {
        baseLayer: (function() {
          var data, url;
          url = 'http://{s}.tile.cloudmade.com/{key}/{styleId}/256/{z}/{x}/{y}.png';
          data = {
            key: "721f5fe14d2a4ae5bf8ecb6412263ce2",
            styleId: 22677
          };
          return L.tileLayer(url, data);
        })()
      };

      return MapModel;

    })(B.Model);
  })(app.module("Models"), Backbone, L);

}).call(this);
